### ISSUE TITLE
Backup loads but folders don't open

### ISSUE THREAD

**Issue by Flofftoff** [MaxiHuHe04/iTunes-Backup-Explorer#67]
My backup seems to open but doesn't load, I'm using 21.0.5-zulu through sdkman / Zulu 21.38+21 99bea6e7-a071-4d33-b6c3-8d272b14d1a0 on an M2 Mac, with full disk access allowed. 
Clicking on folders doesn't do anything, am I missing something?

<img width="912" alt="Screenshot 2024-10-29 at 20 18 55" src="https://github.com/user-attachments/assets/1f634d6f-70da-45be-8dab-fa789c6d7ca1">
<img width="912" alt="Screenshot 2024-10-29 at 20 18 38" src="https://github.com/user-attachments/assets/1c6d1183-028b-4364-9c77-7f4277688d4f">
<img width="912" alt="Screenshot 2024-10-29 at 20 18 44" src="https://github.com/user-attachments/assets/bff4f138-bf8b-4e8a-a581-4674f7c80b59">
<img width="912" alt="Screenshot 2024-10-29 at 20 18 51" src="https://github.com/user-attachments/assets/4c30e65d-2ca1-44a1-9098-d71f330c6c09">

Output:
`boas@MBP14 ~/Downloads [SIGINT]> java -jar itunes-backup-explorer-1.5.jar
Oct 29, 2024 8:18:16 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @49a6e40b'
2024-10-29 20:18:18.342 java[41906:1352672] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-29 20:18:18.343 java[41906:1352672] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
2024-10-29 20:18:22.262 java[41906:1352672] The class 'NSOpenPanel' overrides the method identifier.  This method is implemented by class 'NSWindow'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.sqlite.SQLiteException: [SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:225)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at me.maxih.itunes_backup_explorer.api.ITunesBackup.queryFiles(ITunesBackup.java:205)
	at me.maxih.itunes_backup_explorer.api.ITunesBackup.queryDomainRoots(ITunesBackup.java:247)
	at me.maxih.itunes_backup_explorer.ui.FilesTabController.tabShown(FilesTabController.java:232)
	at me.maxih.itunes_backup_explorer.ui.WindowController.lambda$initialize$0(WindowController.java:74)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:372)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:652)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:670)
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:589)
	at com.sun.javafx.scene.control.behavior.TabPaneBehavior.selectTab(TabPaneBehavior.java:82)
	at javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(TabPaneSkin.java:1529)
	at javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(TabPaneSkin.java:1507)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3985)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1891)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2709)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
^C⏎                                                                     `

**Comment by MaxiHuHe04** [comment]
That's strange. The file database could not be opened. Could you post a screenshot of the contents of the backup directory? You can find it for example using the context menu of the sidebar entry on the left. There should be a Manifest.db file in there. What's the size of it?

**Comment by Flofftoff** [comment]
<img width="746" alt="image" src="https://github.com/user-attachments/assets/f1bd23e4-d0c0-4664-8d66-4d01fe053155">
